version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
      - ./data:/app/data
    working_dir: /app

  streamlit:
    build:
      context: .
      dockerfile: app/streamlit/Dockerfile
    container_name: streamlit_service
    ports:
      - "8502:8501"
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      - api
    volumes:
      - ./model:/app/model
      - ./data:/app/data
    working_dir: /app